In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.linspace(start=0, stop=5, num = 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.68672404, 0.04293748, 0.71842897, 0.34672538, 0.04445913])

In [16]:
np.random.rand(5,5)

array([[0.04749638, 0.1204364 , 0.44630042, 0.85186305, 0.6856811 ],
       [0.22229889, 0.92456056, 0.78857278, 0.58883941, 0.20727703],
       [0.56529907, 0.01148574, 0.34526364, 0.9086975 , 0.01015131],
       [0.75037297, 0.74457772, 0.87775118, 0.63430787, 0.05535252],
       [0.71334007, 0.20573758, 0.89328215, 0.38380691, 0.99220717]])

In [19]:
np.random.randint(1,100,10)

array([81, 40, 40, 73,  1, 73, 46, 85,  4, 10])

In [21]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21, 27, 25, 25, 37, 37,  0, 42, 31, 14])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

42

In [25]:
ranarr.min()

0

In [26]:
ranarr.argmax()

7

In [27]:
arr.shape

(25,)

# indexing and selection

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[0]

0

In [31]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [34]:
arr[0:5]=100#permanent
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
arr = np.arange(11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_copy = arr.copy()

In [39]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[-1,1]

40

In [45]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [50]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [57]:
arr.max()

10